# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cdd9cd3c14519042cf98e09f6c73f0f2e4701ba2f166b6867117b0a51c20b355a80c8631e555a053084df66989caa6f5aa5263f6afa53d2132deec684384c85

test:
  secret_key_base: bd03a9f442b9d7a845eaab1f7a83824ca78605a932f14cd5db65338bb930695e9d9b6cd9e00d76340d10679c8f4454eecfdd2a510d76e5df5fa64084ed05fbf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
